### ISSUE TITLE
OMK Server - OSM attachments don't work in posm-build

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm-build#12]
When installing the server manually, it works fine, even on the same machine. OSM attachments don't make it through when installed via `omk-deploy.sh`.

https://github.com/AmericanRedCross/posm-build/blob/master/kickstart/scripts/omk-deploy.sh

**Comment by jflemer-ndp** [comment]
What paths does it write to and are they configurable?

**Comment by mojodna** [comment]
Apparent differences:

* daemonization
* running as `root` (or other?) vs. `omk`
* `$PATH`

**Comment by hallahan** [comment]
Fixed a long time ago. We're not using issues on this repo anymore.
