### ISSUE TITLE
Fresh Build Fails. 

### ISSUE THREAD

**Issue by jharpster** [AmericanRedCross/posm-build#28]
I suspect things have moved around a bit and scripts have not kept pace with moving directories. 

```npm WARN package.json mapnik@3.5.8 No license field.
/root/scripts/tl-deploy.sh: line 3: 31146 Killed                  npm install mbtiles tilelive-mapnik tilelive-carto tilelive-tmstyle tilelive-tmsource tilelive-file tilelive-http tilelive-mapbox tilejson tilelive-vector tilelive-blend
find: `node_modules/tilelive-vector/node_modules/mapnik': No such file or directory
find: `node_modules/tilelive-mapnik/node_modules/mapnik': No such file or directory
find: `node_modules/mapnik': No such file or directory
find: `node_modules/tilelive-tmsource/node_modules/tilelive-bridge/node_modules/mapnik': No such file or directory
npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-pre-gyp"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! path /root/.npm/node-pre-gyp/0.6.26/package
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir```


Also

>` mapnik@3.5.8 preinstall /usr/lib/node_modules/tessera/node_modules/abaculus/node_modules/mapnik
> npm install node-pre-gyp

npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-pre-gyp"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! path /root/.npm/node-pre-gyp/0.6.26/package
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

**Comment by hallahan** [comment]
Are you as root? What script did you execute?

**Comment by jharpster** [comment]
We think it's this: https://github.com/mapnik/node-mapnik/releases/tag/3.5.8

Running sudo npm install mapnick@3.5.7 works just fine.

**Comment by jharpster** [comment]
Its the tl-deploy.sh script for sure. See attached log. 
[tl-deploy.txt](https://github.com/AmericanRedCross/posm-build/files/209360/tl-deploy.txt)

**Comment by mojodna** [comment]
Was this a fresh USB install? If not, what was the `boostrap.sh` command you run (or multiple, if you did that)? (Order may matter.)

The `npm` log suggests a permissions issue w/ `npm`'s cache, which makes me wonder if you (or something) ran `npm` as a different user first.

What are the permissions on `/root/.npm` and `/root/.npm/node-pre-gyp/0.6.26`?

**Comment by jharpster** [comment]
We created a fresh vagrant Ubuntu 14 VM. Followed the instructions and ran the boostrap.sh as root. The other steps ran through and it bombed on tl.

**Comment by mojodna** [comment]
`npm` 2 + `node-pre-gyp` interact strangely when one becomes root using `sudo -s` (or running things using `sudo` directly), so the root cause of this was that permissions on directories beneath `~posm/.npm` vary between `posm:posm` and `root:root`. Strategic placement of `npm cache clean` helped, but not consistently, so switching back to `npm` 3 is a more reliable fix.
