### ISSUE TITLE
Ease Off osm2pgsql RAM Usage

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/posm-build#4]
`demo_data-deploy.sh` failed on my Small EC2 with 2GB of RAM. It complained that it ran out of RAM while running `osm2pgsql`:

```
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Out of memory for dense node cache, reduce --cache size
Error occurred, cleaning up
```

We resolved this by taking out `-C` which was over aggressively allocating memory. Should we maybe take out `-C` in the script, or will this slow things down too much?

I was able to manually create the render db with:

```
su - gis -c "osm2pgsql --create --hstore-all --hstore-add-index --extra-attributes --slim --drop --unlogged --database=gis --number-processes 1 /tmp/demo_data.pbf"
```
Without `-C`, is `osm2pgsql` smart enough to give an appropriate amount of RAM, or is it defaulting to something super low?

Note, on my EC2, `awk 'NR == 1 { print int($2*.9/1024) } ' /proc/meminfo` gives me `1800`.

It would be nice to have this system run on a Small EC2, because it get's kind of expensive when using fatter EC2s...

cc/ @jflemer-ndp @mojodna

**Comment by jflemer-ndp** [comment]
No problem. I'll skip the `c` option if there isn't much total RAM.
